name       : rsibreak
version    : 0.12.14
release    : 8
source     :
    - https://download.kde.org/stable/rsibreak/0.12/rsibreak-0.12.14.tar.xz : 1ce37ef875ffa1964db80ddb0898b3f762134592f573fabb9950c467b92a5b7a
homepage   : https://userbase.kde.org/RSIBreak
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : RSIBreak takes care of your health and regularly breaks your work to avoid repetitive strain injury (RSI)
description: |
    Repetitive Strain Injury can occur as a result of working with a mouse and keyboard. RSIBreak can be used to remind you to take a break now and then. It displays a random picture from a collection at specified intervals for defined durations. You can configure the pictures to show and lengths of time to show them. You might use the breaks reminders to do some stretching exercises, for example, or as a reminder to walk away from the computer for a while.
builddeps  :
    - pkgconfig(Qt5DBus)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kidletime-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
