name       : rsibreak
version    : 0.12.5
release    : 1
source     :
    - http://download.kde.org/stable/rsibreak/0.12/rsibreak-0.12.5.tar.xz : 4eb134594cbc18f687f534466edce09601a9a4edf370d04d24630008a188b7d1
license    : GPL-2.0
component  : office
summary    : RSIBreak takes care of your health and regularly breaks your work to avoid repetitive strain injury (RSI)
description: |
    RSIBreak takes care of your health and regularly breaks your work to avoid repetitive strain injury (RSI)
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kidletime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
