name       : rsibreak
version    : 0.12.11
release    : 6
source     :
    - https://cdn.download.kde.org/stable/rsibreak/0.12/rsibreak-0.12.11.tar.xz : 1bf2e7d837a0807542b6f505a7fa71aa48e576ef4bb68ad0d4dddeba9e795d25
homepage   : https://userbase.kde.org/RSIBreak
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office
summary    : RSIBreak takes care of your health and regularly breaks your work to avoid repetitive strain injury (RSI)
description: |
    RSIBreak takes care of your health and regularly breaks your work to avoid repetitive strain injury (RSI)
builddeps  :
    - pkgconfig(Qt5DBus)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kidletime-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
